services:
    dmno_monolog.processor.session:
        class: DomUdall\ExtraLoggingBundle\Processor\SessionProcessor
        arguments:  [ @session ]
        tags:
            - { name: monolog.processor }
    dmno_monolog.processor.user:
        class: DomUdall\ExtraLoggingBundle\Processor\UserProcessor
        arguments:  [ @service_container ]
        tags:
            - { name: monolog.processor }
    dmno_monolog.processor.request:
        class: DomUdall\ExtraLoggingBundle\Processor\RequestProcessor
        arguments:  [ @service_container ]
        tags:
            - { name: monolog.processor }
    dmno_monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }